# Generated by Django 5.0.6 on 2024-07-09 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nuevoproject', '0002_alter_actividades_fecha_final_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actividades',
            name='fecha_final',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha final'),
        ),
        migrations.AlterField(
            model_name='actividades',
            name='fecha_inicio',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de inicio'),
        ),
    ]
