# Generated by Django 5.0.6 on 2024-07-13 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nuevoproject', '0005_profesores'),
    ]

    operations = [
        migrations.RenameField(
            model_name='actividades',
            old_name='actividad',
            new_name='metas',
        ),
        migrations.AddField(
            model_name='actividades',
            name='tarea',
            field=models.TextField(null=True),
        ),
    ]
