# Generated by Django 5.0.6 on 2024-07-13 02:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nuevoproject', '0007_materia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actividades',
            name='materia',
        ),
    ]
