# Generated by Django 5.0.6 on 2024-07-13 18:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nuevoproject', '0009_actividades_user_materia_actividad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materia',
            name='actividad',
        ),
        migrations.AddField(
            model_name='actividades',
            name='materia',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nuevoproject.materia'),
        ),
    ]
