# Generated by Django 5.0.6 on 2024-07-14 21:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nuevoproject', '0011_remove_profesores_apellido_remove_profesores_estado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiantes',
            name='nombre',
            field=models.CharField(default=None, max_length=250),
        ),
        migrations.AddField(
            model_name='profesores',
            name='materia',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nuevoproject.materia'),
        ),
        migrations.AddField(
            model_name='profesores',
            name='nombre',
            field=models.CharField(default=None, max_length=250),
        ),
    ]
