# Generated by Django 5.0.6 on 2024-07-15 03:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nuevoproject', '0013_alter_profesores_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profesores_asignados_Estudiantes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nuevoproject.estudiantes')),
                ('profesor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nuevoproject.profesores')),
            ],
        ),
    ]
