# Generated by Django 5.0.6 on 2024-07-15 14:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nuevoproject', '0014_profesores_asignados_estudiantes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Planificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actividades', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nuevoproject.actividades')),
                ('estudiante', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='nuevoproject.estudiantes')),
                ('profesor', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='nuevoproject.profesores')),
            ],
        ),
    ]
