# Generated by Django 5.0.6 on 2024-07-24 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nuevoproject', '0016_alter_planificacion_estudiante'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profesores_asignados_Estudiantes',
        ),
    ]
