# Generated by Django 5.0.6 on 2024-07-24 00:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nuevoproject', '0017_carreras'),
    ]

    operations = [
        migrations.CreateModel(
            name='Materias_por_Carreras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default=None, max_length=250)),
                ('carrera', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='nuevoproject.carreras')),
                ('materia', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='nuevoproject.materia')),
            ],
        ),
    ]
