# Generated by Django 5.0.6 on 2024-07-25 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nuevoproject', '0021_materias_por_carreras'),
    ]

    operations = [
        migrations.AddField(
            model_name='materias_por_carreras',
            name='nombre',
            field=models.CharField(default=None, max_length=250),
        ),
    ]
