# Generated by Django 5.0.6 on 2024-07-29 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nuevoproject', '0022_materias_por_carreras_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiantes',
            name='cedula',
            field=models.PositiveIntegerField(default=None),
        ),
        migrations.AddField(
            model_name='profesores',
            name='cedula',
            field=models.PositiveIntegerField(default=None),
        ),
    ]
