# Generated by Django 5.0.6 on 2024-08-05 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nuevoproject', '0023_estudiantes_cedula_profesores_cedula'),
    ]

    operations = [
        migrations.AddField(
            model_name='profesores',
            name='es_profesor',
            field=models.BooleanField(default=False),
        ),
    ]
