# Generated by Django 5.0.6 on 2024-08-08 18:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nuevoproject', '0024_profesores_es_profesor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notificaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensaje', models.CharField(max_length=250)),
                ('fecha_envio', models.DateTimeField(auto_now_add=True)),
                ('actividad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nuevoproject.actividades')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nuevoproject.estudiantes')),
            ],
        ),
    ]
