# Generated by Django 5.0.6 on 2024-08-08 19:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nuevoproject', '0025_notificaciones'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notificaciones',
            name='actividad',
        ),
        migrations.RemoveField(
            model_name='notificaciones',
            name='fecha_envio',
        ),
        migrations.AddField(
            model_name='notificaciones',
            name='titulo',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='notificaciones',
            name='mensaje',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='notificaciones',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
