# Generated by Django 5.0.6 on 2024-08-08 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nuevoproject', '0026_remove_notificaciones_actividad_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='actividades',
            name='completada',
            field=models.BooleanField(default=False),
        ),
    ]
