# Generated by Django 5.0.6 on 2024-08-09 15:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nuevoproject', '0027_actividades_completada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planificacion',
            name='estudiante',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='nuevoproject.estudiantes'),
        ),
    ]
