# Generated by Django 5.0.6 on 2024-08-28 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nuevoproject', '0029_mensaje_delete_notificaciones'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiantes',
            name='correo',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='profesores',
            name='correo',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
