# Generated by Django 5.0.6 on 2024-08-28 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nuevoproject', '0030_estudiantes_correo_profesores_correo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estudiantes',
            name='correo',
        ),
        migrations.RemoveField(
            model_name='profesores',
            name='correo',
        ),
    ]
