# Generated by Django 5.0.6 on 2024-08-31 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nuevoproject', '0031_remove_estudiantes_correo_remove_profesores_correo'),
    ]

    operations = [
        migrations.AddField(
            model_name='planificacion',
            name='completada',
            field=models.BooleanField(default=False),
        ),
    ]
