# Generated by Django 5.0.6 on 2024-09-02 15:16

import nuevoproject.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nuevoproject', '0032_planificacion_completada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actividades',
            name='metas',
            field=models.TextField(validators=[nuevoproject.validators.NoSpecialCharactersValidator]),
        ),
    ]
