# Generated by Django 5.0.6 on 2024-09-17 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nuevoproject', '0034_alter_actividades_metas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materias_por_carreras',
            name='nombre',
        ),
    ]
