# Generated by Django 5.0.6 on 2024-09-17 17:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nuevoproject', '0035_remove_materias_por_carreras_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensaje',
            name='actividad',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='actividad', to='nuevoproject.actividades'),
        ),
    ]
